import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const url=process.env.VIEWER_URL||'http://127.0.0.1:8767/';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1100},deviceScaleFactor:1});
const failures=[];page.on('pageerror',e=>failures.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push(`${r.status()} ${r.url()}`);});
await mkdir(new URL('../private/',import.meta.url),{recursive:true});
try{
  await page.goto(url);await page.waitForFunction(()=>window.beecamViewer);
  assert.deepEqual(await page.evaluate(()=>window.beecamViewer.inspect()),{members:6,brackets:5,screws:22,nuts:22,platformScrews:8,platformNuts:8,panels:2,stoppers:4,assemblies:{frame:true,platform:true},pattern:true,selected:null,explode:0,hardware:true});
  await page.screenshot({path:new URL('../private/desktop.png',import.meta.url).pathname,fullPage:true});
  await page.locator('#select-frame').click();await page.locator('[data-part="upperArm"]').click();assert.match(await page.locator('#detail-description').innerText(),/provisional/);
  assert.equal(await page.evaluate(()=>window.beecamViewer.inspect().selected),'upperArm');
  await page.locator('#isolate-part').click();assert.equal(await page.locator('.part-label:visible').count(),1);
  await page.locator('#isolate-part').click();
  await page.locator('#hardware-toggle').uncheck();assert.equal(await page.evaluate(()=>window.beecamViewer.inspect().hardware),false);
  await page.locator('#labels-toggle').uncheck();await page.waitForTimeout(80);assert.equal(await page.locator('.part-label:visible').count(),0);
  await page.locator('#explode').fill('65');await page.locator('#explode').dispatchEvent('input');assert.equal(await page.evaluate(()=>window.beecamViewer.inspect().explode),.65);
  for(const view of ['front','side','top','iso'])await page.locator(`[data-camera="${view}"]`).click();
  await page.locator('#reset-view').click();await page.waitForTimeout(80);assert.equal(await page.locator('.part-label:visible').count(),5);
  await page.locator('#frame-toggle').uncheck();assert.equal(await page.evaluate(()=>window.beecamViewer.inspect().assemblies.frame),false);
  await page.locator('#pattern-toggle').uncheck();assert.equal(await page.evaluate(()=>window.beecamViewer.inspect().pattern),false);
  await page.screenshot({path:new URL('../private/uncovered-platform.png',import.meta.url).pathname});
  await page.locator('#reset-view').click();
  await page.locator('[data-part="rearPanel"]').click();await page.locator('#isolate-part').click();assert.equal(await page.locator('.part-label:visible').count(),1);await page.locator('#isolate-part').click();
  await page.locator('#canvas-host').focus();await page.keyboard.press('ArrowRight');
  await page.locator('[data-view="drawings"]').click();
  // Force all lazy-loaded drawings to load for link and rendering validation.
  await page.locator('.drawing-card img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));
  await page.waitForFunction(()=>[...document.querySelectorAll('.drawing-card img')].every(i=>i.complete&&i.naturalWidth>0));
  assert.equal(await page.locator('.drawing-card').count(),21);
  await page.screenshot({path:new URL('../private/drawings.png',import.meta.url).pathname,fullPage:true});
  await page.locator('[data-view="materials"]').click();assert.equal(await page.locator('#bom-body tr').count(),19);
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('a[download][href$=".csv"]').click()]);assert.equal(download.suggestedFilename(),'camera-materials.csv');
  await page.locator('#inside-scope').click();assert.match(await page.locator('#detail-title').innerText(),/enclosure/);
  await page.locator('#whole-scope').click();await page.locator('[data-view="explore"]').click();
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile horizontal overflow');
  await page.locator('#viewer').scrollIntoViewIfNeeded();await page.screenshot({path:new URL('../private/mobile.png',import.meta.url).pathname,fullPage:true});
  await page.locator('#select-frame').click();await page.locator('[data-part="plate"]').click();assert.match(await page.locator('#detail-description').innerText(),/10 mm/);
  await page.locator('#part-drawing').click();assert.equal(await page.locator('#drawings-view').isVisible(),true);
  await page.setViewportSize({width:760,height:850});await page.locator('[data-view="explore"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'tablet horizontal overflow');
  assert.deepEqual(failures,[]);
  console.log('PASS: rendering, geometry counts, selection/isolation, labels, hardware, explosion, camera presets, keyboard orbit, 21 drawings, CSV download, assembly scopes, mobile/tablet layout; no browser errors or failed requests.');
}finally{await browser.close();}
