// Stamp a shared content revision through the application module graph.
// Refreshing the HTML must not combine it with older cached model/data modules.
import {readFile,readdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const root=new URL('../docs/',import.meta.url);
// Reserve exact image space before lazy loading and version regenerated drawings.
const drawingIndex={};
for(const directory of ['drawings','assets'])for(const name of (await readdir(new URL(directory+'/',root))).filter(n=>n.endsWith('.svg')).sort()){
  const path=directory+'/'+name,svg=await readFile(new URL(path,root),'utf8'),tag=svg.match(/<svg\b[^>]*>/)[0];
  const vb=tag.match(/viewBox="([^"]+)"/),numbers=vb?.[1].trim().split(/[ ,]+/).map(Number);
  const width=numbers?.[2]||parseFloat(tag.match(/width="([^"]+)"/)?.[1]),height=numbers?.[3]||parseFloat(tag.match(/height="([^"]+)"/)?.[1]);
  if(!width||!height)throw new Error('Missing SVG dimensions: '+path);
  drawingIndex[path]={width,height,revision:createHash('sha256').update(svg).digest('hex').slice(0,12)};
}
const indexText='// Generated by version-assets.mjs; prevents lazy-image layout shifts.\nexport default '+JSON.stringify(drawingIndex,null,2)+';\n';
const indexPath=new URL('js/drawing-index.js',root);
if(process.argv.includes('--check')){if(await readFile(indexPath,'utf8')!==indexText)throw new Error('Stale drawing index');}
else await writeFile(indexPath,indexText);
const files=(await readdir(new URL('js/',root))).filter(f=>f.endsWith('.js')).sort();
const clean=s=>s.replace(/\?v=[a-f0-9]{12}/g,'');
const sources=new Map();
const hash=createHash('sha256');
for(const f of files){const s=clean(await readFile(new URL('js/'+f,root),'utf8'));sources.set(f,s);hash.update(f+'\0'+s);}
hash.update(await readFile(new URL('style.css',root)));
for(const f of (await readdir(new URL('assets/',root))).sort())hash.update(await readFile(new URL('assets/'+f,root)));
const revision=hash.digest('hex').slice(0,12);
const outputs=new Map();
for(const [f,s]of sources){
  // Vendor modules are unchanged and retain their shared identity.
  const stamped=s.replace(/(['"])(\.\/[^'"?]+\.js|\.\.\/assets\/[^'"?]+\.svg)\1/g,(_,q,path)=>`${q}${path}?v=${revision}${q}`);
  outputs.set('js/'+f,stamped);
}
const html=clean(await readFile(new URL('index.html',root),'utf8'));
outputs.set('index.html',html.replace('href="style.css"',`href="style.css?v=${revision}"`).replace('src="js/app.js"',`src="js/app.js?v=${revision}"`));
for(const [file,expected]of outputs){
  const path=new URL(file,root),actual=await readFile(path,'utf8');
  if(process.argv.includes('--check')){if(actual!==expected)throw new Error(`Stale asset revision: ${file}. Run node scripts/version-assets.mjs.`);}
  else if(actual!==expected)await writeFile(path,expected);
}
console.log(`${process.argv.includes('--check')?'PASS: consistent':'Stamped'} application asset revision ${revision}.`);
